# Schwerpunktfach Wirtschaft und Recht (1gPW) {.unnumbered}

In diesem Repository werden die Informationen für den Unterricht im
Schwerpunktfach Wirtschaft und Recht zur Verfügung gestellt.

## Programm {.unnumbered}

Das Programm entspricht dem aktuellen Stand der Planung. Es kann zu
Änderungen kommen.


| Datum | Thema |
| ----- | ----- |
| 18.08.2026 | Einstieg und Semesterüberblick |
| 19.08.2026 | BWL Wirtschaftliche Grundbegriffe |
| 21.08.2026 | BWL Ökonomisches Prinzip und Wertschöpfung |
| 25.08.2026 | BWL Wertschöpfungsketten |
| 26.08.2026 | BWL Unternehmungsarten I |
| 28.08.2026 | BWL Unternehmungsarten II |
| 01.09.2026 | BWL Fallbeispiele Grundbegriffe |
| 02.09.2026 | BWL Unternehmungsmodell I |
| 04.09.2026 | BWL Unternehmungsmodell II |
| 08.09.2026 | BWL Unternehmungsmodell III |
| 09.09.2026 | BWL Anwendung Unternehmungsmodell |
| 11.09.2026 | BWL Vertiefung und Prüfungsvorbereitung |
| 15.09.2026 | Prüfung 1: BWL Grundbegriffe bis Unternehmungsmodell |
| 16.09.2026 | BWL Organisation I |
| 18.09.2026 | BWL Organisation II |
| 22.09.2026 | BWL Personal I |
| 23.09.2026 | BWL Personal II |
| 25.09.2026 | BWL Abschluss: Fallstudie |
| 20.10.2026 | FRW Einführung Rechnungswesen |
| 21.10.2026 | Prüfung 2: BWL Organisation und Personal |
| 23.10.2026 | FRW Bilanz |
| 27.10.2026 | FRW Bilanzübungen |
| 28.10.2026 | FRW Erfolgsrechnung |
| 30.10.2026 | FRW Konten und Kontenrahmen |
| 03.11.2026 | FRW Buchungssätze |
| 04.11.2026 | FRW Buchungsdrill I |
| 06.11.2026 | FRW Buchungsdrill II |
| 10.11.2026 | FRW Journal und Hauptbuch |
| 11.11.2026 | FRW Doppelter Erfolgsnachweis |
| 13.11.2026 | FRW Abschlussübungen Grundlagen |
| 17.11.2026 | FRW Warenhandel: Warenkonten |
| 18.11.2026 | FRW Warenhandel: Verbuchung |
| 20.11.2026 | FRW Warenhandel: Bestandesänderungen |
| 24.11.2026 | FRW Kalkulation: Grundschema |
| 25.11.2026 | FRW Einzelkalkulation |
| 27.11.2026 | FRW Gesamtkalkulation |
| 01.12.2026 | FRW Kalkulationsübungen |
| 02.12.2026 | FRW Buchungsdrill Warenhandel |
| 04.12.2026 | FRW Abschluss: vernetzte Übungen |
| 08.12.2026 | Recht Einstieg: Was ist Recht? |
| 09.12.2026 | Prüfung 3: FRW Doppelte Buchhaltung und Kalkulation |
| 11.12.2026 | Recht Rechtsordnung |
| 15.12.2026 | Recht Rechtsquellen und Gesetzesaufbau |
| 16.12.2026 | Recht Falllösemethodik |
| 18.12.2026 | Recht Rechtsanwendung: Strafrecht exemplarisch |
| 05.01.2027 | Recht Grundzüge der Rechtspflege |
| 06.01.2027 | Recht Übungen Falllösung |
| 08.01.2027 | Recht Personenrecht: Rechtsfähigkeit |
| 12.01.2027 | Recht Personenrecht: Handlungsfähigkeit |
| 13.01.2027 | Recht Handlungsfähigkeit: Fälle |
| 15.01.2027 | Recht Juristische Personen |
| 19.01.2027 | Recht Vereinsrecht |
| 20.01.2027 | Recht Vertiefung und Prüfungsvorbereitung |
| 22.01.2027 | Prüfung 4: Recht Grundlagen und Personenrecht |
| 26.01.2027 | Recht Vereinsrecht: Statuten-Werkstatt |
| 27.01.2027 | Recht Falllösungen quer |
| 29.01.2027 | Recht Aktualitäten |
| 02.02.2027 | Recht Ausblick OR AT |
| 03.02.2027 | Recht Vernetzte Fallstudie |
| 05.02.2027 | Semesterabschluss |


## Hilfsmittel für den Unterricht {.unnumbered}

Der Unterricht basiert auf den Lehrmitteln Krummenacher/Thoemmen,
Einführung in die Betriebswirtschaftslehre, Leimgruber/Prochinig,
Rechnungswesen, sowie einer Studienausgabe von ZGB und OR. Hier werden
zu gegebener Zeit weitere Informationen bzw. Unterlagen zur Verfügung gestellt.


## Beurteilung {.unnumbered}

Die Note wird aus dem Durchschnitt der schriftlichen Prüfungen
sowie der Benotung der mündlichen Beteiligung berechnet. Der
Durchschnitt der Prüfungen zählt zu 90%, die mündliche Beteiligung zu
10%.  

Falls jemand eine persönliche Besprechung wünscht, 
<a href="https://calendar.app.google/UynTL5ttVPHhK1Hc8" target="_blank">
kann hier einen Termin für eine Sprechstunde reserviert werden
(Rent-A-Mock)</a>.
